# Generated by Django 2.2.3 on 2019-07-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190712_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(null=True)),
                ('imdbId', models.IntegerField()),
                ('islike', models.BooleanField()),
            ],
        ),
    ]
